# Generated by Django 4.2.1 on 2023-05-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_book_author_book_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='Author',
        ),
        migrations.AddField(
            model_name='book',
            name='Author',
            field=models.ManyToManyField(to='books.author'),
        ),
    ]
